# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import django

sys.path.insert(0, os.path.abspath("../../project_example"))

# Set default settings for django project
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project_example.settings.docs")

# Initialize django conf
django.setup()

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "project example"
copyright = "2024, Author Name"
author = "Author Name"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
]

add_module_names = False
"""
Set short name of modules and classes
"""

autodoc_typehints = "both"

autosummary_generate = True

intersphinx_mapping = {
    "python310": ("https://docs.python.org/3.10", None),
}

templates_path = ["_templates"]
"""
Add any paths that contain templates here, relative to this directory.
"""
exclude_patterns = []
"""
List of patterns, relative to source directory, that match files and
directories to ignore when looking for source files.
This pattern also affects html_static_path and html_extra_path.
"""

language = "en"
"""
The language for content autogenerated by Sphinx. Refer to documentation
for a list of supported languages.

This is also used if you do content translation via gettext catalogs.
Usually you set "language" from the command line for these cases.
"""

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "alabaster"
html_static_path = ["_static"]
"""
Add any paths that contain custom static files (such as style sheets) here,
relative to this directory. They are copied after the builtin static files,
so a file named "default.css" will overwrite the builtin "default.css".
"""
html_css_files = [
    "func_params.css",
]

html_favicon = None
"""
favicon.ico for generated html, expected favicon path `_static/favicon.ico`,
while favicon.ico is undefined balue must be None
"""
